server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.101.104:3306/movie?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size:
        1024MB
      max-request-size:
        2048MB
mybatis:
  type-aliases-package: com.shixun.entity
  mapper-locations:
  - classpath:/mapper/*Mapper.xml

